// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SocialMediaApp.Models;

public partial class User
{
    [Key]
    [Column("UserID")]
    public int UserId { get; set; }

    [Required(ErrorMessage ="you should put your name [:")]
    [StringLength(50)]
    [Unicode(false)]
    public string UserName { get; set; }

    [Required(ErrorMessage ="Email is Required")]
    [StringLength(100)]
    [Unicode(false)]
    public string Email { get; set; }

    [Required(ErrorMessage ="you must write your password")]
    [StringLength(100)]
    [Unicode(false)]
    public string Password { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string ProfilePhoto { get; set; }



    [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
    public DateOnly? BirthDate { get; set; }




    [InverseProperty("User")]
    public virtual ICollection<Post> Posts { get; set; } = new List<Post>();


    
    [StringLength(20)]
    public string Role { get; set; } = "user";


}